services:
  - type: web
    name: skyguardian-backend
    env: python
    plan: free
    region: frankfurt  
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: PORT
        value: 8000